"""Database access layer for the ``fact_inventory`` table.

Notes
-----
Repositories encapsulate all database-specific query logic including raw SQL constructs,
dialect-specific hints, window functions, and query optimization. This layer isolates
the application from storage details, allowing the schema and query strategies to evolve
without changing business logic in services or endpoints.
"""

import logging
from typing import Any

from advanced_alchemy.repository import SQLAlchemyAsyncRepository
from sqlalchemy import delete, func, select

from fact_inventory.domain.retention import HistoryRetentionPolicy, TimeRetentionPolicy
from fact_inventory.infrastructure.db.models import FactInventory

__all__ = ["FactInventoryRepository"]


class FactInventoryRepository(SQLAlchemyAsyncRepository[FactInventory]):
    """Database access layer for the fact_inventory table.

    Methods here contain database-specific query logic (raw SQL
    constructs, dialect hints, etc.). Application rules belong in
    FactInventoryService.
    """

    model_type = FactInventory

    async def insert_record(self, data: dict[str, Any]) -> FactInventory:
        """Insert a new fact inventory record into the database.

        Creates a new record with the provided fact data. Multiple rows may
        exist for the same client_address - each call creates a new row with
        a unique UUID generated by the database.

        Parameters
        ----------
        data : dict[str, Any]
            Dictionary containing client_address, system_facts,
            package_facts, and local_facts.

        Returns
        -------
        FactInventory
            The created record instance with all attributes populated.

        Raises
        ------
        RepositoryError
            If the record could not be created (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        instance = self.model_type(**data)
        result = await self.add(instance)
        logging.getLogger(__name__).info("New fact record inserted")
        return result

    async def upsert_client_record(self, data: dict[str, Any]) -> FactInventory:
        """Create or update a fact inventory record for a client_address.

        Matching is based on client_address - if a record exists for
        the same IP it is updated in place and updated_at is refreshed;
        otherwise a new record is created.

        Parameters
        ----------
        data : dict[str, Any]
            Dictionary containing client_address, system_facts,
            package_facts, and local_facts.

        Returns
        -------
        FactInventory
            The created or updated record instance with all attributes populated.

        Raises
        ------
        RepositoryError
            If the record could not be created or updated.
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        instance = self.model_type(**data)
        result = await self.upsert(
            data=instance,
            match_fields=["client_address"],
        )
        logging.getLogger(__name__).info("Fact record upserted")
        return result

    async def delete_facts_older_than(self, policy: TimeRetentionPolicy) -> int:
        """Delete all fact records whose updated_at predates the policy cutoff.

        Parameters
        ----------
        policy : TimeRetentionPolicy
            Time retention policy providing the cutoff datetime.

        Returns
        -------
        int
            Number of rows deleted.

        Raises
        ------
        RepositoryError
            If the record could not be deleted (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        cutoff = policy.cutoff_datetime
        stmt = delete(self.model_type).where(self.model_type.updated_at < cutoff)
        result = await self.session.execute(stmt)
        deleted_count = getattr(result, "rowcount", 0) or 0
        if deleted_count:
            await self.session.commit()
            logging.getLogger(__name__).info("Record pruning completed")
        return deleted_count

    async def delete_old_client_facts_over_limit(
        self, policy: HistoryRetentionPolicy
    ) -> int:
        """Delete oldest fact records per client_address exceeding the retention limit.

        Keeps the newest max_entries per client_address by using a window
        function to rank records within each client_address partition, then
        deleting those beyond the policy's max_entries threshold.

        Parameters
        ----------
        policy : HistoryRetentionPolicy
            History retention policy specifying maximum records per client_address.

        Returns
        -------
        int
            Number of rows deleted.

        Raises
        ------
        RepositoryError
            If the record could not be deleted (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        max_entries = policy.max_entries

        # Window function: rank records per client_address, newest first
        row_num = func.row_number().over(
            partition_by=self.model_type.client_address,
            order_by=self.model_type.created_at.desc(),
        )

        # Subquery identifying which record is at which rank
        subq = select(self.model_type.id, row_num.label("rn")).subquery()

        # Delete records beyond the max_entries threshold
        stmt = delete(self.model_type).where(
            self.model_type.id.in_(select(subq.c.id).where(subq.c.rn > max_entries))
        )
        result = await self.session.execute(stmt)
        deleted_count = getattr(result, "rowcount", 0) or 0
        if deleted_count:
            await self.session.commit()
            logging.getLogger(__name__).info("Record pruning completed")
        return deleted_count
